version: "3.7"
services:
#  Create a service named pentaho.
  pentaho:
    build:
     context: configs
     dockerfile: Dockerfile
    image: kespinosa05/pentaho:9.0-alpine3113
    environment:
     - TIMEZONE=America/Montevideo
    ports:
     - "8081:8080"
    networks:
     - integration

#  Create a service named postgres.
  postgres:
#   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres:10"
#   Give the container the postgres container name. You can changes to something else.
    container_name: "postgres_10"
#   Setup the username, password, and database name. You can changes these values.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#   Maps port 5432 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "5432:5432"
#   Set a volume some that database is not lost after shutting down the container.
#   I used the name postgres-data but you can changed it to something else.
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data:z
      - ./configs/scripts/1.sql:/docker-entrypoint-initdb.d/1.sql:z
      - ./configs/scripts/2.sql:/docker-entrypoint-initdb.d/2.sql:z
      - ./configs/scripts/3.sql:/docker-entrypoint-initdb.d/3.sql:z
      - ./configs/scripts/4.sql:/docker-entrypoint-initdb.d/4.sql:z
    networks:
     - integration

networks:
  integration:
      driver: bridge
      ipam:
        driver: default
        config:
         - subnet: 178.148.0.0/16
